server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8

security:
  oauth2:
    client:
      client-id: ssoclient
      client-secret: ssosecret
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token
      jwt:
        key-uri: http://localhost:8080/oauth/token_key

securityconfig:
  logoutsuccssurl: /tosignout
  permitall: /rest/**,/re**
  deniedpage: /deny
  urlroles: /**/new/** = admin;
            /**/edit/** = admin,editor;
            /**/delete/** = admin


