server:
  port: 8083
  tomcat:
    uri-encoding: UTF-8
# datasource
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/mytest?characterEncoding=utf8&useSSL=false
      username: root
      password: 12345678
  jpa:
    database: MYSQL
    show-sql: true
  ## Hibernate ddl auto (validate|create|create-drop|update)
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        enable_lazy_load_no_trans: true


security:
  oauth2:
    client:
      client-id: ssoclient
      client-secret: ssosecret
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token
#      jwt:
#        key-uri: http://localhost:8080/oauth/token_key

